### ISSUE TITLE
It required `Y` enter

### ISSUE THREAD

**Issue by kamontat** [menny/docker_android#1]
But I run on in `circleci`, there is any thing to fixed?

**Comment by kamontat** [comment]
![screen shot 2560-05-17 at 7 00 17 pm](https://cloud.githubusercontent.com/assets/14089557/26152905/3ca216c2-3b33-11e7-9def-9522bef628e3.png)

**Comment by menny** [comment]
Can you send me the circleci yaml and a link to a build on circleci?

**Comment by kamontat** [comment]
Sorry, I fixed already. Thank you so much

**Comment by menny** [comment]
@kamontat, I'm curious, what was the fix?

**Comment by kamontat** [comment]
This long time ago hahaha. 
Since Circle-ci (v2) isn't official support android yet, but I can run Junit completely so I think androidTest should run complete too, but I'm wrong, so I try to change to Circle-ci (v1) and use their implementing android emulator

PS your `start_emulator.sh` can't work, but I can't remember why it's can't, sorry
