### ISSUE TITLE
latest tag

### ISSUE THREAD

**Issue by Isanderthul** [menny/docker_android#3]
Hi. There is no latest tag, so I had to do `docker pull menny/android_ndk:1.9.0`

**Comment by menny** [comment]
Damn it! Will fix. Thanks for notifying .

I always pull a versioned image, so I didn't notice

**Comment by Isanderthul** [comment]
thanks :)

**Comment by menny** [comment]
`latest` is available now: https://hub.docker.com/r/menny/android/tags/
